config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "events#index"

  get "/feed", to: "feed#index"

  resources :users do
    resources :subscriptions, only: [:index, :create, :destroy]
  end

  resources :events do
    resources :event_attendencees
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :event_attendencees

  validates :name, presence: true
  validates :description, presence: true
  validates :adress, presence: true
  validates :starts_at, comparison: { greater_than: DateTime.now,
                                      message: "can't be earlier then today date" }
  validates :ends_at, comparison: { greater_than: :starts_at ,
                                    message: "can't be earlier then start date" }
end

app/models/event_attendencee.rb
class EventAttendencee < ApplicationRecord
  belongs_to :attendencee, class_name: "User"
  belongs_to :event
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :subscriber, class_name: "User"
  belongs_to :subscribed_user, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, class_name: 'Event', foreign_key: 'creator_id', dependent: :destroy
  has_many :event_attendencees, class_name: "EventAttendencee", foreign_key: "attendencee_id", dependent: :destroy

  has_many :subscriptions_as_subscriber, class_name: "Subscription", foreign_key: "subscriber_id", dependent: :destroy
  has_many :subscriptions_as_subscribed_user, class_name: "Subscription", foreign_key: "subscribed_user_id", dependent: :destroy

  has_many :subscribers, through: :subscriptions_as_subscribed_user
  has_many :subscribed_users, through: :subscriptions_as_subscriber

  validates :username, length: {minimum:4, maximum:10}

  scope :subscribed_users, ->(user_id) {where(id: user_id).joins(:subscriptions_as_subscriber).select(:subscribed_user_id)}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/event_attendencees_controller.rb
class EventAttendenceesController < ApplicationController
before_action :authenticate_user!
before_action :set_event

def new
  @atendencee = EventAttendencee.new
end


def create
  @attendencee = EventAttendencee.new(event_id: @event.id, attendencee_id: current_user.id)

  if @attendencee.save
    redirect_to event_path(@event)
  else
    render :new, status: :unprocessable_entity
  end
end

private

 def set_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    # change to all upcoming events
    @events = Event.all
  end

  def show
   @event = Event.find(params[:id])
   @attendences = @event.event_attendencees
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    current_user.events << @event

    if @event.save
      redirect_to events_path
      flash[:success] = "#{@event.name} created sccuessfuly!"
    else
      flash.now[:error] = "Rats! Fix your mistakes, please."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    puts "destroy"
    Event.find(params[:id]).destroy
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :adress, :starts_at, :ends_at)
  end

end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  before_action :authenticate_user!

  def index
    @events = Event.where(creator_id: [ User.subscribed_users(current_user.id)])
    p @events
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :define_users
  before_action :user_subscribed?, only: [:create]
  def index
    @subscription = Subscription.where(subscribed_user_id: @subscribed_user.id)
  end

  def create
    subscription = Subscription.new(subscribed_user_id: @subscribed_user.id, subscriber_id: @user.id)

    if subscription.save
      flash.now[:success]="You subribed to #{@subscribed_user.username}"
    end
  end

  def destroy
     Subscription.where(subscribed_user_id: @subscribed_user.id, subscriber_id: @user.id).first.delete
  end

  private

  def define_users
    @user = User.find(current_user.id)
    @subscribed_user = User.find(params[:user_id])
  end

  def user_subscribed?
    unless Subscription.where(subscribed_user_id: @subscribed_user.id, subscriber_id: @user.id) == []
      flash[:error]="You can't subscribe for the same user twice!"
      render template: "user/#{@user.id}"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :define_user_events, only: [:show]
  before_action :current_user_subscribed?, only: [:show]
  before_action :find_subscribers, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  private

  def define_user_events
    @feauture_events = current_user.events.where("starts_at > ?", DateTime.now)
    @past_events = current_user.events.where("ends_at < ?", DateTime.now)
    @current_events_attandencee = Event.where("ends_at > ?", DateTime.now)
                               .and(Event.where("starts_at < ?", DateTime.now))
                               .joins(:event_attendencees)
                               .where("attendencee_id = ?", params[:id])
    @prev_events_attandencee = Event.where("ends_at < ?", DateTime.now)
                               .joins(:event_attendencees)
                               .where("attendencee_id = ?", params[:id])
    @feaut_events_attandencee = Event.where("starts_at > ?", DateTime.now)
                               .joins(:event_attendencees)
                               .where("attendencee_id = ?", params[:id])
  end

  def current_user_subscribed?
    @subscribed = Subscription.where(subscribed_user_id: params[:id], subscriber_id: current_user.id) == []
  end

  def find_subscribers
    @subscribers = User.find(params[:id]).subscribers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendencees_helper.rb
module EventAttendenceesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendencees/new.html.erb
<%= button_to "Become attendencee", event_event_attendencees_path(params[:event_id]), method: :post %>

app/views/events/_error_message.html.erb
<% event.errors.full_messages_for(field).each do |message| %>
      <div><%= message %></div>
<% end %>

app/views/events/index.html.erb
<h1>Welcome to Private events!</h1>
<% @events.each do |event| %>
  <h3> <%= event.name %> </h3>
  <p> <%= event.description %> </p>
  <%= link_to 'See more', event_path(event) %>
<% end %>

app/views/events/new.html.erb
<h1> Create your own event </h1>

<div>
  <% if !flash.blank? %>
    <% flash.each do |type, message| %>
      <div class=type><%= message %></div>
    <% end %>
  <% end %>
</div>

<%= form_with model: @event do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= render 'error_message', event: @event, field: :name %>
    <%= f.text_field :name, autofocus: true %><br />
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= render 'error_message', event: @event, field: :description %>
    <%= f.text_field :description, autofocus: true %><br />
  </div>
  <div class="field">
    <%= f.label :adress %><br />
    <%= render 'error_message', event: @event, field: :adress %>
    <%= f.text_field :adress, autofocus: true %><br />
  </div>
  <div>
    <div class="field">
      <%= f.label :starts_at %><br />
      <%= render 'error_message', event: @event, field: :starts_at %>
      <%= f.date_field :starts_at, autofocus: true %><br />
    </div>
    <div class="field">
      <%= f.label :ends_at %><br />
      <%= render 'error_message', event: @event, field: :ends_at %>
      <%= f.date_field :ends_at, autofocus: true %><br />
    </div>
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/events/show.html.erb
<h1> <%= @event.name %> </h1>
<div> 
    <h2> creator: <%= @event.creator.username %> </h2>
    <div>
        start: <%= @event.starts_at %>
        end: <%= @event.ends_at %> 
    </div>
</div>
<p> <%= @event.description %> </p>

 <% if @event.creator_id == current_user&.id %>
        <%= button_to "Delete event",
          event_path(id: @event.id), 
          method: :delete, 
          data: { turbo_confirm: "Are you sure?" } 
        %>
 <% end %>

 <% if user_signed_in? %>
 <%# if current_user.id == @event.creator_id %>
    <p> Attendences: </p>
    <ul>
    <% @attendences.each do |attendencee| %>
      <li> <%= User.find(attendencee.attendencee_id).username %> </li>
    <% end %>
    
 <% end %>
 

<% if user_signed_in? %>
    <%= link_to 'Become event attendencee', new_event_event_attendencee_path(@event.id) %>
<% else %>
    <p> To become attendencee and see other attendencies you have to sign in</p>
<% end %>

app/views/feed/index.html.erb
<h1>Feed</h1>
<% @events.each do |event| %>
  <h3> <%= event.name %> </h3>
  <p> <%= event.description %> </p>
  <%= link_to 'See more', event_path(event) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to 'All events', events_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Profile', user_path(current_user) %></li>
          <li><%= link_to 'Feed', feed_path %></li>
          <li><%= button_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.username %>'s page</h1>

<h3>Subscribers</h3>

<% if !@subscribers.blank? %>
  <% for subscriber in @subscribers %>
    <%= link_to "#{subscriber.username}", user_path(subscriber) %>
  <% end %>
  <% else %>
  <p><%= @user.username %> has no subscribers</p>
<% end %>


<% if !user_signed_in? %>
  <p> Sign in to subscribe for <%= @user.username %></p>
<% elsif @user.id == current_user.id %>
  <%= link_to 'Create event', new_event_path %>
<% elsif @subscribed %>
  <%= button_to "Subscribe", user_subscriptions_path(user_id: params[:id]) %>
<% else %>
  <%= button_to "Unsubscribe", user_subscription_path(user_id: params[:id]), method: :delete %>
<% end %>

<h3>Events</h3>

<ul>
  <% if !@user.events.blank? %> 
    <% for event in @user.events %>
      <li><%= event.name %> <%= link_to 'See more', event %></li>
      <% if @user.id == current_user.id %>
        <%= button_to "Delete event",
          event_path(id: event.id), 
          method: :delete, 
          data: { turbo_confirm: "Are you sure?" } 
        %>
      <% end %>
    <% end %> 
  <% end %>
</ul>


    <h4>Feauture events</h4>
    <ul>
      <% if !@feauture_events.blank? %> 
        <% for event in @feauture_events %>
          <li><%= event.name %></li>
        <% end %> 
      <% end %>
    </ul>

    <h4>Previous events</h4>
    <ul>
      <% if !@pased_events.blank? %> 
        <% for event in @pased_events %>
          <li><%= event.name %></li>
        <% end %> 
      <% else %>
        <p>There wasn't any events before</p>
      <% end %>
    </ul>


    <h3>Particepates in events as attendancee</h3>
    <ul>
      <% if !@current_events_attandencee.blank? %>
        <% for event in @current_events_attandencee %>
          <li><%= event.name %></li>
        <% end %> 
      <% else %>
        <p>Now <%= @user.username %> free</p>
      <% end %>
    </ul>


    <h3>Will Particepate in events as attendancee</h3>
    <ul>
      <% if !@feaut_events_attandencee.blank? %>
        <% for event in @feaut_events_attandencee %>
          <li><%= event.name %></li>
        <% end %> 
      <% else %>
        <p><%= @user.username %> is not going to come to any event</p>
      <% end %>
    </ul>


    <h3>Particepated in events as attendancee</h3>
    <ul>
      <% if !@prev_events_attandencee.blank? %> 
        <% for event in @prev_events_attandencee %>
          <li><%= event.name %></li>
        <% end %> 
      <% else %>
        <p>There wasn't any events where <%= @user.username %> particapated</p>
      <% end %>
    </ul>